### ISSUE TITLE
Some cards are truncated in the PDF

### ISSUE THREAD

**Issue by Nahor** [ad-si/Rust-Flashcards#3]
Some cards are truncated in the PDF. 

Some examples:
- Page 110 (loop labels), where the code is truncated but one could think it's just
- Page 114 ("Looping through a collection like this is a bad idea. Give 2 reasons why.") only shows the first part of the detailed explanation ("error prone") and not the 2nd ("slow").
- Page 116 ("What is a better and more concise alternative to loop over the array?"), missing the last sentence ("The safety and conciseness of for loops ...")
- Page 128 ("What happens in terms of the heap and stack when we assign s1 to s2 in line 2?") only show part of the "s1" variable and nothing of "s2" or the heap.
- ...

**Comment by ad-si** [comment]
Thanks for the heads up!

Fixed in 0e8693c and 85eb28c7258e232a93623e984e5ffcd2ed68e631.
