### ISSUE TITLE
Invalid answer/question in PDF page 180-182

### ISSUE THREAD

**Issue by Nahor** [ad-si/Rust-Flashcards#4]
PDF page 180 ("What's a possible error inducing operation on string slice range indices?"), I'm not sure what the `first_word` function is supposed to be:
1. It returns a usize, not a slice, even though that area of the deck is about slices,
2. If it's supposed to show a problem with slicing in between UTF-8 character, b' ' is a single byte character, so it's valid to slice at that boundary (it would be invalid if `item` was in the range 0x80-0xBF, i.e. of the form 0x10xxxxxx)
3. If it's the beginning of the page 181 question, then it's at the wrong place (but then also see next point of this issue)

page 181/182:
It mentions a `first_word` function, but if the function from page 180, then see point 1 above, which _does_ compile since `word` is then the usize `5`, and not a reference to the "`hello`" slice.

**Comment by ad-si** [comment]
Thanks for the heads up!

It was the beginning of the next question.
I added a better example and fixed the first_word function.

Fixed in 3e528b5.
