### ISSUE TITLE
Rust flashcard

### ISSUE THREAD

**Issue by Zhyfengss** [ad-si/Rust-Flashcards#5]

**Comment by ad-si** [comment]
@Zhyfengss I think you might have forgotten your issue body? 😅

**Comment by Zhyfengss** [comment]
I really thank you for creating such a useful tool. I was in the process of
testing and carelessly commented in the article


Отправлено с мобильного устройства

**Comment by ad-si** [comment]
Thanks, glad you enjoy it! 😊
Happy learning!
