### ISSUE TITLE
No License File

### ISSUE THREAD

**Issue by adagio256** [ad-si/Rust-Flashcards#9]
Repositories with sharable content should contain licenses.

**Comment by eljamm** [comment]
https://choosealicense.com/no-permission/

**Comment by adagio256** [comment]
https://www.lib.uchicago.edu/copyrightinfo/fairuse.html

**Comment by eljamm** [comment]
I'm not a lawyer, but isn't the link you've posted about:

> Using copyrighted material in your teaching

While what we're talking about here is a license for the project in general?

**Comment by adagio256** [comment]
I am more-so wondering about how to license derivative works I may want to publish as my own.

**Comment by adagio256** [comment]
If the authors have a license preference I would respect that otherwise closing the question since it's all non-commercial for learning purposes.

**Comment by eljamm** [comment]
We still haven't heard the author's opinion on this, though.

@ad-si May we discuss adding a license to the project?

**Comment by ad-si** [comment]
Sorry for being absent from the discussion. I’d like to add a license as well, but I’m not sure since a lot is copied from the book and other anki decks.

**Comment by adbagio** [comment]
I'm not a lawyer here. Personally I see the reuse of content as non-commercial fair-use. Perhaps a permissive non-commercial share-and-share alike creative-commons license would provide an indication to that effect?

**Comment by adagio256** [comment]
I'm not a lawyer here. I see the reuse of content as clearly non-commercial fair-use. Perhaps a permissive non-commercial share-and-share alike creative-commons license would provide an indication to that effect?

**Comment by eljamm** [comment]
Once again, I'm not a lawyer, but as far as the rust-book is concerned, I think it's alright to use it since it's dual-licensed under MIT and Apache-2.0.

As for the other Anki decks. Perhaps we can contact their authors and ask if it's alright if their work is included? This might also depend on how much of their work is indluded.

Whatever we do, though. I think it's far better to add a license than not to, since the project is already up and the code is available anyways.

**Comment by adagio256** [comment]
For the code portions, I'm not a lawyer, but I do think copying the license files and generally indicating which parts are covered should be done. I don't see how there is any clearly fair use of technical components even if the project is non-commercial etc.

Maybe I, as not a lawyer, wouldn't worry about the cards content except to perhaps add something to the effect of it being shared as non-commercial.

**Comment by ad-si** [comment]
I checked again how much came from the book and how much from other sources, and I think it's close enough to the book to designate it as the only source. So I simply used only the MIT license (as seen in 74e1634).

Thanks again for your help!

**Comment by adagio256** [comment]
I've been checking documentation and code snippets in text are MIT licensed like here: https://gtk-rs.org/gtk4-rs/stable/latest/book/introduction.html#license
